CREATE TABLE `operation` (
  `id` varchar(128) NOT NULL,
  `operation` varchar(255) DEFAULT NULL,
  `error_rate` varchar(255) DEFAULT NULL,
  `unit` varchar(255) DEFAULT NULL,
  `min` varchar(255) DEFAULT NULL,
  `median` varchar(255) DEFAULT NULL,
  `max` varchar(255) DEFAULT NULL,
  `flush_time` varchar(255) DEFAULT NULL,
  `flush_time_shard` varchar(255) DEFAULT NULL,
  `memory_doc_value` varchar(255) DEFAULT NULL,
  `memory_norms` varchar(255) DEFAULT NULL,
  `memory_segments` varchar(255) DEFAULT NULL,
  `memory_stored_field` varchar(255) DEFAULT NULL,
  `memory_terms` varchar(255) DEFAULT NULL,
  `old_gc_time` varchar(255) DEFAULT NULL,
  `young_gc_time` varchar(255) DEFAULT NULL,
  `refresh_time` varchar(255) DEFAULT NULL,
  `segment_count` varchar(255) DEFAULT NULL,
  `total_time` varchar(255) DEFAULT NULL,
  `total_time_per_shard` varchar(255) DEFAULT NULL,
  `translog_size` varchar(255) DEFAULT NULL,
  `merge_throttle_time` varchar(255) DEFAULT NULL,
  `merge_throttle_time_per_shard_max` varchar(255) DEFAULT NULL,
  `merge_time` varchar(255) DEFAULT NULL,
  `merge_time_per_shard_max` varchar(255) DEFAULT NULL,
  `trial_timestamp` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
);